@startuml

actor Пользователь as user
participant "Сервис бронирования" as servis
database "База данных" as db

activate user
activate servis

user->servis: Заходит в сервис
user<--servis: Выводит схему расположения комнат. Просит\nввести дату, кол-во человек и необходимое\nоборудование

opt Информация о комнате
    user->servis: Нажимает/наводит на комнату
    activate db
    servis->db: Запрос на вывод актуальной информации\nпо выбранной комнате
    servis<--db: Актуальная информация по комнате
    deactivate db
    user<--servis: Выводит информацию о комнате
end

user->servis: Вводит дату, кол-во человек, отмечает\nнеобходимое оборудование и нажимает "Поиск"

activate db
servis->db: Запрос на выборку подходящих комнат\nи занятых часовых интервалов
servis<--db: Список подходящих комнат и занятых\nчасовых интервалов
deactivate db

servis->servis: Рассчитать свободные часовые интервалы

alt Есть доступные варианты
    user<--servis: Вывести доступные варианты бронирования
else Нет доступных вариантов
    user<--servis: Вывести сообщение "Нет свободных комнат\nна указанную дату. Показать ближайшие\nдоступные варианты?"

    opt Выбрал показать варианты
        user->servis: Нажимает "Показать варианты"

        activate db
        servis->db: Запрос на выборку подходящих комнат\nи занятых часовых интервалов на ближайшие\nдаты
        servis<--db: Список подходящих комнат и занятых\nчасовых интервалов
        deactivate db

        servis->servis: Рассчитать свободные часовые интервалы

        alt Есть ближайшие доступные варианты
            user<--servis: Вывести ближайшие доступные варианты\nбронирования
        else Нет ближайших доступных вариантов
            user<--servis: Вывести сообщение "Нет подходящих свободных\nкомнат. Измените параметры поиска и попробуйте\nещё раз"
            note right of user : процесс завершён
        end
    end
end

user->servis: Нажимает на один/несколько последовательных\nпонравившихся временных интервалов и на кнопку\n"Забронировать"
user<--servis: Вывести сообщение "Подтвердить бронирование\n(повторить название комнаты, дату, время, кол-во\nчеловек, оборудование)?"

alt Подтвердил бронь
    user->servis: Нажимает "Да"

    activate db
    servis->db: Запрос на проверку доступности комнаты\nпо указанным условиям

    alt Комната свободна
        servis<--db: Комната свободна
        servis->db: Запрос на создание новой брони
        servis<--db: Бронь успешно создана
        user<--servis: Вывести сообщение "Вы забронировали комнату\n(повторить название комнаты, дату, время,\nкол-во человек, оборудование)"
    else Комната занята
        servis<--db: Комната занята
        user<--servis: Вывести сообщение "Бронирование недоступно.\nКомнату успел забронировать кто-то другой"
        note right of user : процесс завершён
    end

    deactivate db

else Не подтвердил бронь
    user->servis: Нажимает "Нет"
    note right of user : процесс завершён
end

deactivate user
deactivate servis

@enduml
